// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Me struct {
	UserID string  `json:"userID"`
	OrgID  string  `json:"orgID"`
	Role   string  `json:"role"`
	Name   *string `json:"name,omitempty"`
	Email  *string `json:"email,omitempty"`
}

type Query struct {
}
