// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: attachments.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const createRequestAttachment = `-- name: CreateRequestAttachment :one

INSERT INTO public.request_attachments (
  org_id,
  request_id,
  filename,
  content_type,
  size_bytes,
  sha256,
  storage_key,
  uploaded_by_user_id
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, org_id, request_id, filename, content_type, size_bytes, sha256, storage_key, uploaded_by_user_id, created_at
`

type CreateRequestAttachmentParams struct {
	OrgID            uuid.UUID     `json:"org_id"`
	RequestID        uuid.UUID     `json:"request_id"`
	Filename         string        `json:"filename"`
	ContentType      string        `json:"content_type"`
	SizeBytes        int64         `json:"size_bytes"`
	Sha256           string        `json:"sha256"`
	StorageKey       string        `json:"storage_key"`
	UploadedByUserID uuid.NullUUID `json:"uploaded_by_user_id"`
}

// MVP-070: Read Model queries for request attachments
func (q *Queries) CreateRequestAttachment(ctx context.Context, arg CreateRequestAttachmentParams) (RequestAttachment, error) {
	row := q.db.QueryRowContext(ctx, createRequestAttachment,
		arg.OrgID,
		arg.RequestID,
		arg.Filename,
		arg.ContentType,
		arg.SizeBytes,
		arg.Sha256,
		arg.StorageKey,
		arg.UploadedByUserID,
	)
	var i RequestAttachment
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.RequestID,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.Sha256,
		&i.StorageKey,
		&i.UploadedByUserID,
		&i.CreatedAt,
	)
	return i, err
}

const getRequestAttachmentByOrgRequestAndID = `-- name: GetRequestAttachmentByOrgRequestAndID :one
SELECT id, org_id, request_id, filename, content_type, size_bytes, sha256, storage_key, uploaded_by_user_id, created_at
FROM public.request_attachments
WHERE org_id = $1 AND request_id = $2 AND id = $3
`

type GetRequestAttachmentByOrgRequestAndIDParams struct {
	OrgID     uuid.UUID `json:"org_id"`
	RequestID uuid.UUID `json:"request_id"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) GetRequestAttachmentByOrgRequestAndID(ctx context.Context, arg GetRequestAttachmentByOrgRequestAndIDParams) (RequestAttachment, error) {
	row := q.db.QueryRowContext(ctx, getRequestAttachmentByOrgRequestAndID, arg.OrgID, arg.RequestID, arg.ID)
	var i RequestAttachment
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.RequestID,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.Sha256,
		&i.StorageKey,
		&i.UploadedByUserID,
		&i.CreatedAt,
	)
	return i, err
}

const listRequestAttachmentsByOrgAndRequestID = `-- name: ListRequestAttachmentsByOrgAndRequestID :many
SELECT id, org_id, request_id, filename, content_type, size_bytes, sha256, storage_key, uploaded_by_user_id, created_at
FROM public.request_attachments
WHERE org_id = $1 AND request_id = $2
ORDER BY created_at DESC
`

type ListRequestAttachmentsByOrgAndRequestIDParams struct {
	OrgID     uuid.UUID `json:"org_id"`
	RequestID uuid.UUID `json:"request_id"`
}

func (q *Queries) ListRequestAttachmentsByOrgAndRequestID(ctx context.Context, arg ListRequestAttachmentsByOrgAndRequestIDParams) ([]RequestAttachment, error) {
	rows, err := q.db.QueryContext(ctx, listRequestAttachmentsByOrgAndRequestID, arg.OrgID, arg.RequestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RequestAttachment{}
	for rows.Next() {
		var i RequestAttachment
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.RequestID,
			&i.Filename,
			&i.ContentType,
			&i.SizeBytes,
			&i.Sha256,
			&i.StorageKey,
			&i.UploadedByUserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
