// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_log_queries.sql

package dbgen

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const searchAuditLogs = `-- name: SearchAuditLogs :many
SELECT id, org_id, request_id, actor_user_id, action, data, occurred_at
FROM public.request_audit_trail
WHERE org_id = $1
  AND ($2::uuid IS NULL OR request_id = $2::uuid)
  AND ($3::uuid IS NULL OR actor_user_id = $3::uuid)
  AND ($4::text IS NULL OR action = $4::text)
  AND ($5::timestamptz IS NULL OR occurred_at >= $5::timestamptz)
  AND ($6::timestamptz IS NULL OR occurred_at <= $6::timestamptz)
ORDER BY occurred_at DESC
LIMIT $8
OFFSET $7
`

type SearchAuditLogsParams struct {
	OrgID           uuid.UUID      `json:"org_id"`
	RequestID       uuid.NullUUID  `json:"request_id"`
	ActorUserID     uuid.NullUUID  `json:"actor_user_id"`
	Action          sql.NullString `json:"action"`
	OccurredAtStart sql.NullTime   `json:"occurred_at_start"`
	OccurredAtEnd   sql.NullTime   `json:"occurred_at_end"`
	OffsetCount     int32          `json:"offset_count"`
	LimitCount      int32          `json:"limit_count"`
}

type SearchAuditLogsRow struct {
	ID          uuid.UUID       `json:"id"`
	OrgID       uuid.UUID       `json:"org_id"`
	RequestID   uuid.UUID       `json:"request_id"`
	ActorUserID uuid.NullUUID   `json:"actor_user_id"`
	Action      string          `json:"action"`
	Data        json.RawMessage `json:"data"`
	OccurredAt  time.Time       `json:"occurred_at"`
}

func (q *Queries) SearchAuditLogs(ctx context.Context, arg SearchAuditLogsParams) ([]SearchAuditLogsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchAuditLogs,
		arg.OrgID,
		arg.RequestID,
		arg.ActorUserID,
		arg.Action,
		arg.OccurredAtStart,
		arg.OccurredAtEnd,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchAuditLogsRow{}
	for rows.Next() {
		var i SearchAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.RequestID,
			&i.ActorUserID,
			&i.Action,
			&i.Data,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
