// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: comments.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const insertComment = `-- name: InsertComment :one
INSERT INTO request_comments (org_id, request_id, user_id, content)
VALUES ($1, $2, $3, $4)
RETURNING id, org_id, request_id, user_id, content, created_at
`

type InsertCommentParams struct {
	OrgID     uuid.UUID `json:"org_id"`
	RequestID uuid.UUID `json:"request_id"`
	UserID    uuid.UUID `json:"user_id"`
	Content   string    `json:"content"`
}

func (q *Queries) InsertComment(ctx context.Context, arg InsertCommentParams) (RequestComment, error) {
	row := q.db.QueryRowContext(ctx, insertComment,
		arg.OrgID,
		arg.RequestID,
		arg.UserID,
		arg.Content,
	)
	var i RequestComment
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.RequestID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const insertCommentIfNotExists = `-- name: InsertCommentIfNotExists :exec
INSERT INTO request_comments (id, org_id, request_id, user_id, content, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (id) DO NOTHING
`

type InsertCommentIfNotExistsParams struct {
	ID        uuid.UUID `json:"id"`
	OrgID     uuid.UUID `json:"org_id"`
	RequestID uuid.UUID `json:"request_id"`
	UserID    uuid.UUID `json:"user_id"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) InsertCommentIfNotExists(ctx context.Context, arg InsertCommentIfNotExistsParams) error {
	_, err := q.db.ExecContext(ctx, insertCommentIfNotExists,
		arg.ID,
		arg.OrgID,
		arg.RequestID,
		arg.UserID,
		arg.Content,
		arg.CreatedAt,
	)
	return err
}

const listCommentsByRequest = `-- name: ListCommentsByRequest :many

SELECT id, org_id, request_id, user_id, content, created_at
FROM request_comments
WHERE org_id = $1 AND request_id = $2
ORDER BY created_at ASC
`

type ListCommentsByRequestParams struct {
	OrgID     uuid.UUID `json:"org_id"`
	RequestID uuid.UUID `json:"request_id"`
}

// LEARN-022F: SQL queries for request comments
func (q *Queries) ListCommentsByRequest(ctx context.Context, arg ListCommentsByRequestParams) ([]RequestComment, error) {
	rows, err := q.db.QueryContext(ctx, listCommentsByRequest, arg.OrgID, arg.RequestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RequestComment{}
	for rows.Next() {
		var i RequestComment
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.RequestID,
			&i.UserID,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
