// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dashboard.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const avgTimeToApproval = `-- name: AvgTimeToApproval :one
SELECT 
  COALESCE(AVG(EXTRACT(EPOCH FROM (decided_at - submitted_at))), 0)::double precision AS avg_seconds,
  COUNT(*)::bigint AS sample_count
FROM public.requests
WHERE org_id = $1 
  AND status = 'approved'
  AND submitted_at IS NOT NULL
  AND decided_at IS NOT NULL
`

type AvgTimeToApprovalRow struct {
	AvgSeconds  float64 `json:"avg_seconds"`
	SampleCount int64   `json:"sample_count"`
}

func (q *Queries) AvgTimeToApproval(ctx context.Context, orgID uuid.UUID) (AvgTimeToApprovalRow, error) {
	row := q.db.QueryRowContext(ctx, avgTimeToApproval, orgID)
	var i AvgTimeToApprovalRow
	err := row.Scan(&i.AvgSeconds, &i.SampleCount)
	return i, err
}

const countRequestsByMonth = `-- name: CountRequestsByMonth :many
SELECT 
  DATE_TRUNC('month', created_at)::timestamptz AS month, 
  COUNT(*)::bigint AS count
FROM public.requests
WHERE org_id = $1
  AND ($2::timestamptz IS NULL OR created_at >= $2::timestamptz)
  AND ($3::timestamptz IS NULL OR created_at <= $3::timestamptz)
GROUP BY month
ORDER BY month DESC
`

type CountRequestsByMonthParams struct {
	OrgID     uuid.UUID    `json:"org_id"`
	StartDate sql.NullTime `json:"start_date"`
	EndDate   sql.NullTime `json:"end_date"`
}

type CountRequestsByMonthRow struct {
	Month time.Time `json:"month"`
	Count int64     `json:"count"`
}

func (q *Queries) CountRequestsByMonth(ctx context.Context, arg CountRequestsByMonthParams) ([]CountRequestsByMonthRow, error) {
	rows, err := q.db.QueryContext(ctx, countRequestsByMonth, arg.OrgID, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountRequestsByMonthRow{}
	for rows.Next() {
		var i CountRequestsByMonthRow
		if err := rows.Scan(&i.Month, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countRequestsByStatus = `-- name: CountRequestsByStatus :many

SELECT status, COUNT(*) AS count
FROM public.requests
WHERE org_id = $1
GROUP BY status
ORDER BY status
`

type CountRequestsByStatusRow struct {
	Status string `json:"status"`
	Count  int64  `json:"count"`
}

// Dashboard statistics queries
func (q *Queries) CountRequestsByStatus(ctx context.Context, orgID uuid.UUID) ([]CountRequestsByStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, countRequestsByStatus, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountRequestsByStatusRow{}
	for rows.Next() {
		var i CountRequestsByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDashboardSummary = `-- name: GetDashboardSummary :one
SELECT 
  COUNT(*) FILTER (WHERE status = 'draft')::bigint AS draft_count,
  COUNT(*) FILTER (WHERE status = 'submitted')::bigint AS submitted_count,
  COUNT(*) FILTER (WHERE status = 'approved')::bigint AS approved_count,
  COUNT(*) FILTER (WHERE status = 'rejected')::bigint AS rejected_count,
  COUNT(*)::bigint AS total_count,
  COALESCE(AVG(EXTRACT(EPOCH FROM (decided_at - submitted_at))) FILTER (WHERE status = 'approved' AND submitted_at IS NOT NULL AND decided_at IS NOT NULL), 0)::double precision AS avg_approval_seconds
FROM public.requests
WHERE org_id = $1
`

type GetDashboardSummaryRow struct {
	DraftCount         int64   `json:"draft_count"`
	SubmittedCount     int64   `json:"submitted_count"`
	ApprovedCount      int64   `json:"approved_count"`
	RejectedCount      int64   `json:"rejected_count"`
	TotalCount         int64   `json:"total_count"`
	AvgApprovalSeconds float64 `json:"avg_approval_seconds"`
}

func (q *Queries) GetDashboardSummary(ctx context.Context, orgID uuid.UUID) (GetDashboardSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, getDashboardSummary, orgID)
	var i GetDashboardSummaryRow
	err := row.Scan(
		&i.DraftCount,
		&i.SubmittedCount,
		&i.ApprovedCount,
		&i.RejectedCount,
		&i.TotalCount,
		&i.AvgApprovalSeconds,
	)
	return i, err
}
