// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: event_store.sql

package dbgen

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const appendEvent = `-- name: AppendEvent :one
WITH current AS (
  SELECT COALESCE(MAX(version), 0)::int AS version
  FROM public.event_store
  WHERE org_id = $1
    AND aggregate_type = $2
    AND aggregate_id = $3
)
INSERT INTO public.event_store (
  org_id,
  aggregate_type,
  aggregate_id,
  version,
  event_type,
  payload,
  metadata
)
SELECT
  $1::uuid AS org_id,
  $2::text AS aggregate_type,
  $3::uuid AS aggregate_id,
  $4::int AS version,
  $5::text AS event_type,
  $6::jsonb AS payload,
  $7::jsonb AS metadata
FROM current
WHERE current.version = ($4 - 1)
RETURNING id, org_id, aggregate_type, aggregate_id, version, event_type, payload, metadata, occurred_at
`

type AppendEventParams struct {
	Column1 uuid.UUID       `json:"column_1"`
	Column2 string          `json:"column_2"`
	Column3 uuid.UUID       `json:"column_3"`
	Column4 int32           `json:"column_4"`
	Column5 string          `json:"column_5"`
	Column6 json.RawMessage `json:"column_6"`
	Column7 json.RawMessage `json:"column_7"`
}

type AppendEventRow struct {
	ID            uuid.UUID       `json:"id"`
	OrgID         uuid.UUID       `json:"org_id"`
	AggregateType string          `json:"aggregate_type"`
	AggregateID   uuid.UUID       `json:"aggregate_id"`
	Version       int32           `json:"version"`
	EventType     string          `json:"event_type"`
	Payload       json.RawMessage `json:"payload"`
	Metadata      json.RawMessage `json:"metadata"`
	OccurredAt    time.Time       `json:"occurred_at"`
}

func (q *Queries) AppendEvent(ctx context.Context, arg AppendEventParams) (AppendEventRow, error) {
	row := q.db.QueryRowContext(ctx, appendEvent,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
	)
	var i AppendEventRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AggregateType,
		&i.AggregateID,
		&i.Version,
		&i.EventType,
		&i.Payload,
		&i.Metadata,
		&i.OccurredAt,
	)
	return i, err
}

const getAggregateVersion = `-- name: GetAggregateVersion :one

SELECT COALESCE(MAX(version), 0)::int AS version
FROM public.event_store
WHERE org_id = $1
  AND aggregate_type = $2
  AND aggregate_id = $3
`

type GetAggregateVersionParams struct {
	OrgID         uuid.UUID `json:"org_id"`
	AggregateType string    `json:"aggregate_type"`
	AggregateID   uuid.UUID `json:"aggregate_id"`
}

// MVP-021: event_store append / load
func (q *Queries) GetAggregateVersion(ctx context.Context, arg GetAggregateVersionParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, getAggregateVersion, arg.OrgID, arg.AggregateType, arg.AggregateID)
	var version int32
	err := row.Scan(&version)
	return version, err
}

const getEventsByAggregateID = `-- name: GetEventsByAggregateID :many
SELECT id, org_id, aggregate_type, aggregate_id, version, event_type, payload, metadata, occurred_at
FROM public.event_store
WHERE aggregate_id = $1
ORDER BY version ASC
`

type GetEventsByAggregateIDRow struct {
	ID            uuid.UUID       `json:"id"`
	OrgID         uuid.UUID       `json:"org_id"`
	AggregateType string          `json:"aggregate_type"`
	AggregateID   uuid.UUID       `json:"aggregate_id"`
	Version       int32           `json:"version"`
	EventType     string          `json:"event_type"`
	Payload       json.RawMessage `json:"payload"`
	Metadata      json.RawMessage `json:"metadata"`
	OccurredAt    time.Time       `json:"occurred_at"`
}

func (q *Queries) GetEventsByAggregateID(ctx context.Context, aggregateID uuid.UUID) ([]GetEventsByAggregateIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getEventsByAggregateID, aggregateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEventsByAggregateIDRow{}
	for rows.Next() {
		var i GetEventsByAggregateIDRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.AggregateType,
			&i.AggregateID,
			&i.Version,
			&i.EventType,
			&i.Payload,
			&i.Metadata,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByAggregate = `-- name: ListEventsByAggregate :many
SELECT id, org_id, aggregate_type, aggregate_id, version, event_type, payload, metadata, occurred_at
FROM public.event_store
WHERE org_id = $1
  AND aggregate_type = $2
  AND aggregate_id = $3
  AND version >= $4
ORDER BY version ASC
`

type ListEventsByAggregateParams struct {
	OrgID         uuid.UUID `json:"org_id"`
	AggregateType string    `json:"aggregate_type"`
	AggregateID   uuid.UUID `json:"aggregate_id"`
	Version       int32     `json:"version"`
}

type ListEventsByAggregateRow struct {
	ID            uuid.UUID       `json:"id"`
	OrgID         uuid.UUID       `json:"org_id"`
	AggregateType string          `json:"aggregate_type"`
	AggregateID   uuid.UUID       `json:"aggregate_id"`
	Version       int32           `json:"version"`
	EventType     string          `json:"event_type"`
	Payload       json.RawMessage `json:"payload"`
	Metadata      json.RawMessage `json:"metadata"`
	OccurredAt    time.Time       `json:"occurred_at"`
}

func (q *Queries) ListEventsByAggregate(ctx context.Context, arg ListEventsByAggregateParams) ([]ListEventsByAggregateRow, error) {
	rows, err := q.db.QueryContext(ctx, listEventsByAggregate,
		arg.OrgID,
		arg.AggregateType,
		arg.AggregateID,
		arg.Version,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventsByAggregateRow{}
	for rows.Next() {
		var i ListEventsByAggregateRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.AggregateType,
			&i.AggregateID,
			&i.Version,
			&i.EventType,
			&i.Payload,
			&i.Metadata,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
