// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: idempotency.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const getIdempotencyByKey = `-- name: GetIdempotencyByKey :one
SELECT org_id, actor_user_id, action, idempotency_key, request_hash, status_code, response_body, created_at
FROM idempotency
WHERE org_id = $1 AND actor_user_id = $2 AND action = $3 AND idempotency_key = $4
`

type GetIdempotencyByKeyParams struct {
	OrgID          uuid.UUID `json:"org_id"`
	ActorUserID    uuid.UUID `json:"actor_user_id"`
	Action         string    `json:"action"`
	IdempotencyKey string    `json:"idempotency_key"`
}

func (q *Queries) GetIdempotencyByKey(ctx context.Context, arg GetIdempotencyByKeyParams) (Idempotency, error) {
	row := q.db.QueryRowContext(ctx, getIdempotencyByKey,
		arg.OrgID,
		arg.ActorUserID,
		arg.Action,
		arg.IdempotencyKey,
	)
	var i Idempotency
	err := row.Scan(
		&i.OrgID,
		&i.ActorUserID,
		&i.Action,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.StatusCode,
		&i.ResponseBody,
		&i.CreatedAt,
	)
	return i, err
}

const insertIdempotencyIfNotExists = `-- name: InsertIdempotencyIfNotExists :execrows
INSERT INTO idempotency (
    org_id,
    actor_user_id,
    action,
    idempotency_key,
    request_hash,
    status_code,
    response_body,
    created_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, NOW())
ON CONFLICT (org_id, actor_user_id, action, idempotency_key) DO NOTHING
`

type InsertIdempotencyIfNotExistsParams struct {
	OrgID          uuid.UUID `json:"org_id"`
	ActorUserID    uuid.UUID `json:"actor_user_id"`
	Action         string    `json:"action"`
	IdempotencyKey string    `json:"idempotency_key"`
	RequestHash    string    `json:"request_hash"`
	StatusCode     int32     `json:"status_code"`
	ResponseBody   string    `json:"response_body"`
}

func (q *Queries) InsertIdempotencyIfNotExists(ctx context.Context, arg InsertIdempotencyIfNotExistsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertIdempotencyIfNotExists,
		arg.OrgID,
		arg.ActorUserID,
		arg.Action,
		arg.IdempotencyKey,
		arg.RequestHash,
		arg.StatusCode,
		arg.ResponseBody,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateIdempotencyResponse = `-- name: UpdateIdempotencyResponse :exec
UPDATE idempotency
SET request_hash = $5, status_code = $6, response_body = $7
WHERE org_id = $1 AND actor_user_id = $2 AND action = $3 AND idempotency_key = $4
`

type UpdateIdempotencyResponseParams struct {
	OrgID          uuid.UUID `json:"org_id"`
	ActorUserID    uuid.UUID `json:"actor_user_id"`
	Action         string    `json:"action"`
	IdempotencyKey string    `json:"idempotency_key"`
	RequestHash    string    `json:"request_hash"`
	StatusCode     int32     `json:"status_code"`
	ResponseBody   string    `json:"response_body"`
}

func (q *Queries) UpdateIdempotencyResponse(ctx context.Context, arg UpdateIdempotencyResponseParams) error {
	_, err := q.db.ExecContext(ctx, updateIdempotencyResponse,
		arg.OrgID,
		arg.ActorUserID,
		arg.Action,
		arg.IdempotencyKey,
		arg.RequestHash,
		arg.StatusCode,
		arg.ResponseBody,
	)
	return err
}
