// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package dbgen

import (
	"time"
)

type PonsuMigrationsSmoketest struct {
	ID        int32     `json:"id"`
	CreatedAt time.Time `json:"created_at"`
}
