// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package dbgen

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type EventStore struct {
	ID             uuid.UUID       `json:"id"`
	OrgID          uuid.UUID       `json:"org_id"`
	AggregateType  string          `json:"aggregate_type"`
	AggregateID    uuid.UUID       `json:"aggregate_id"`
	Version        int32           `json:"version"`
	EventType      string          `json:"event_type"`
	Payload        json.RawMessage `json:"payload"`
	Metadata       json.RawMessage `json:"metadata"`
	OccurredAt     time.Time       `json:"occurred_at"`
	GlobalPosition int64           `json:"global_position"`
}

type Membership struct {
	OrgID     uuid.UUID `json:"org_id"`
	UserID    uuid.UUID `json:"user_id"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Organization struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Permission struct {
	ID          string    `json:"id"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
}

type PonsuMigrationsSmoketest struct {
	ID        int32     `json:"id"`
	CreatedAt time.Time `json:"created_at"`
}

type ProjectionCheckpoint struct {
	OrgID         uuid.UUID `json:"org_id"`
	ProjectorName string    `json:"projector_name"`
	LastPosition  int64     `json:"last_position"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type ProjectorDemoAggregateVersion struct {
	OrgID         uuid.UUID `json:"org_id"`
	AggregateType string    `json:"aggregate_type"`
	AggregateID   uuid.UUID `json:"aggregate_id"`
	LastVersion   int32     `json:"last_version"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type Request struct {
	ID              uuid.UUID     `json:"id"`
	OrgID           uuid.UUID     `json:"org_id"`
	Title           string        `json:"title"`
	Status          string        `json:"status"`
	CreatedByUserID uuid.NullUUID `json:"created_by_user_id"`
	DecidedByUserID uuid.NullUUID `json:"decided_by_user_id"`
	CreatedAt       time.Time     `json:"created_at"`
	UpdatedAt       time.Time     `json:"updated_at"`
	SubmittedAt     sql.NullTime  `json:"submitted_at"`
	DecidedAt       sql.NullTime  `json:"decided_at"`
}

type RequestAttachment struct {
	ID               uuid.UUID     `json:"id"`
	OrgID            uuid.UUID     `json:"org_id"`
	RequestID        uuid.UUID     `json:"request_id"`
	Filename         string        `json:"filename"`
	ContentType      string        `json:"content_type"`
	SizeBytes        int64         `json:"size_bytes"`
	Sha256           string        `json:"sha256"`
	StorageKey       string        `json:"storage_key"`
	UploadedByUserID uuid.NullUUID `json:"uploaded_by_user_id"`
	CreatedAt        time.Time     `json:"created_at"`
}

type RequestAuditTrail struct {
	ID                  uuid.UUID       `json:"id"`
	OrgID               uuid.UUID       `json:"org_id"`
	RequestID           uuid.UUID       `json:"request_id"`
	ActorUserID         uuid.NullUUID   `json:"actor_user_id"`
	Action              string          `json:"action"`
	Data                json.RawMessage `json:"data"`
	OccurredAt          time.Time       `json:"occurred_at"`
	EventGlobalPosition sql.NullInt64   `json:"event_global_position"`
}

type RequestStep struct {
	RequestID        uuid.UUID     `json:"request_id"`
	StepIndex        int32         `json:"step_index"`
	Label            string        `json:"label"`
	Status           string        `json:"status"`
	AssignedToUserID uuid.NullUUID `json:"assigned_to_user_id"`
	UpdatedAt        time.Time     `json:"updated_at"`
}

type RolePermission struct {
	Role         string    `json:"role"`
	PermissionID string    `json:"permission_id"`
	CreatedAt    time.Time `json:"created_at"`
}

type User struct {
	ID         uuid.UUID `json:"id"`
	OidcIssuer string    `json:"oidc_issuer"`
	OidcSub    string    `json:"oidc_sub"`
	Email      string    `json:"email"`
	Name       string    `json:"name"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type WorkflowTemplate struct {
	ID              uuid.UUID       `json:"id"`
	OrgID           uuid.UUID       `json:"org_id"`
	Name            string          `json:"name"`
	Description     string          `json:"description"`
	Definition      json.RawMessage `json:"definition"`
	CreatedByUserID uuid.NullUUID   `json:"created_by_user_id"`
	CreatedAt       time.Time       `json:"created_at"`
	UpdatedAt       time.Time       `json:"updated_at"`
}
