// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification_templates.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const getNotificationTemplate = `-- name: GetNotificationTemplate :one
SELECT id, org_id, event_type, template_body, created_at, updated_at
FROM notification_templates
WHERE org_id = $1 AND event_type = $2
LIMIT 1
`

type GetNotificationTemplateParams struct {
	OrgID     uuid.UUID `json:"org_id"`
	EventType string    `json:"event_type"`
}

func (q *Queries) GetNotificationTemplate(ctx context.Context, arg GetNotificationTemplateParams) (NotificationTemplate, error) {
	row := q.db.QueryRowContext(ctx, getNotificationTemplate, arg.OrgID, arg.EventType)
	var i NotificationTemplate
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.EventType,
		&i.TemplateBody,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertNotificationTemplate = `-- name: UpsertNotificationTemplate :one
INSERT INTO notification_templates (org_id, event_type, template_body)
VALUES ($1, $2, $3)
ON CONFLICT (org_id, event_type)
DO UPDATE SET template_body = EXCLUDED.template_body, updated_at = NOW()
RETURNING id, org_id, event_type, template_body, created_at, updated_at
`

type UpsertNotificationTemplateParams struct {
	OrgID        uuid.UUID `json:"org_id"`
	EventType    string    `json:"event_type"`
	TemplateBody string    `json:"template_body"`
}

func (q *Queries) UpsertNotificationTemplate(ctx context.Context, arg UpsertNotificationTemplateParams) (NotificationTemplate, error) {
	row := q.db.QueryRowContext(ctx, upsertNotificationTemplate, arg.OrgID, arg.EventType, arg.TemplateBody)
	var i NotificationTemplate
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.EventType,
		&i.TemplateBody,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
