// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projector.sql

package dbgen

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const getProjectionCheckpoint = `-- name: GetProjectionCheckpoint :one

SELECT org_id, projector_name, last_position, updated_at
FROM public.projection_checkpoints
WHERE org_id = $1 AND projector_name = $2
`

type GetProjectionCheckpointParams struct {
	OrgID         uuid.UUID `json:"org_id"`
	ProjectorName string    `json:"projector_name"`
}

// MVP-022: projector (synchronous projection)
func (q *Queries) GetProjectionCheckpoint(ctx context.Context, arg GetProjectionCheckpointParams) (ProjectionCheckpoint, error) {
	row := q.db.QueryRowContext(ctx, getProjectionCheckpoint, arg.OrgID, arg.ProjectorName)
	var i ProjectionCheckpoint
	err := row.Scan(
		&i.OrgID,
		&i.ProjectorName,
		&i.LastPosition,
		&i.UpdatedAt,
	)
	return i, err
}

const listEventsForProjector = `-- name: ListEventsForProjector :many
SELECT id, org_id, aggregate_type, aggregate_id, version, global_position, event_type, payload, metadata, occurred_at
FROM public.event_store
WHERE org_id = $1
  AND global_position > $2
ORDER BY global_position ASC
LIMIT $3
`

type ListEventsForProjectorParams struct {
	OrgID          uuid.UUID `json:"org_id"`
	GlobalPosition int64     `json:"global_position"`
	Limit          int32     `json:"limit"`
}

type ListEventsForProjectorRow struct {
	ID             uuid.UUID       `json:"id"`
	OrgID          uuid.UUID       `json:"org_id"`
	AggregateType  string          `json:"aggregate_type"`
	AggregateID    uuid.UUID       `json:"aggregate_id"`
	Version        int32           `json:"version"`
	GlobalPosition int64           `json:"global_position"`
	EventType      string          `json:"event_type"`
	Payload        json.RawMessage `json:"payload"`
	Metadata       json.RawMessage `json:"metadata"`
	OccurredAt     time.Time       `json:"occurred_at"`
}

func (q *Queries) ListEventsForProjector(ctx context.Context, arg ListEventsForProjectorParams) ([]ListEventsForProjectorRow, error) {
	rows, err := q.db.QueryContext(ctx, listEventsForProjector, arg.OrgID, arg.GlobalPosition, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventsForProjectorRow{}
	for rows.Next() {
		var i ListEventsForProjectorRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.AggregateType,
			&i.AggregateID,
			&i.Version,
			&i.GlobalPosition,
			&i.EventType,
			&i.Payload,
			&i.Metadata,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDemoAggregateVersion = `-- name: UpsertDemoAggregateVersion :one
INSERT INTO public.projector_demo_aggregate_versions (org_id, aggregate_type, aggregate_id, last_version)
VALUES ($1, $2, $3, $4)
ON CONFLICT (org_id, aggregate_type, aggregate_id) DO UPDATE
SET last_version = EXCLUDED.last_version,
    updated_at = now()
RETURNING org_id, aggregate_type, aggregate_id, last_version, updated_at
`

type UpsertDemoAggregateVersionParams struct {
	OrgID         uuid.UUID `json:"org_id"`
	AggregateType string    `json:"aggregate_type"`
	AggregateID   uuid.UUID `json:"aggregate_id"`
	LastVersion   int32     `json:"last_version"`
}

// Demo projection: store last version per aggregate.
func (q *Queries) UpsertDemoAggregateVersion(ctx context.Context, arg UpsertDemoAggregateVersionParams) (ProjectorDemoAggregateVersion, error) {
	row := q.db.QueryRowContext(ctx, upsertDemoAggregateVersion,
		arg.OrgID,
		arg.AggregateType,
		arg.AggregateID,
		arg.LastVersion,
	)
	var i ProjectorDemoAggregateVersion
	err := row.Scan(
		&i.OrgID,
		&i.AggregateType,
		&i.AggregateID,
		&i.LastVersion,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertProjectionCheckpoint = `-- name: UpsertProjectionCheckpoint :one
INSERT INTO public.projection_checkpoints (org_id, projector_name, last_position)
VALUES ($1, $2, $3)
ON CONFLICT (org_id, projector_name) DO UPDATE
SET last_position = EXCLUDED.last_position,
    updated_at = now()
RETURNING org_id, projector_name, last_position, updated_at
`

type UpsertProjectionCheckpointParams struct {
	OrgID         uuid.UUID `json:"org_id"`
	ProjectorName string    `json:"projector_name"`
	LastPosition  int64     `json:"last_position"`
}

func (q *Queries) UpsertProjectionCheckpoint(ctx context.Context, arg UpsertProjectionCheckpointParams) (ProjectionCheckpoint, error) {
	row := q.db.QueryRowContext(ctx, upsertProjectionCheckpoint, arg.OrgID, arg.ProjectorName, arg.LastPosition)
	var i ProjectionCheckpoint
	err := row.Scan(
		&i.OrgID,
		&i.ProjectorName,
		&i.LastPosition,
		&i.UpdatedAt,
	)
	return i, err
}
