// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rbac.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO public.organizations (name)
VALUES ($1)
RETURNING id, name
`

type CreateOrganizationRow struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) CreateOrganization(ctx context.Context, name string) (CreateOrganizationRow, error) {
	row := q.db.QueryRowContext(ctx, createOrganization, name)
	var i CreateOrganizationRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getAnyMembershipByUserID = `-- name: GetAnyMembershipByUserID :one
SELECT org_id, user_id, role
FROM public.memberships
WHERE user_id = $1
ORDER BY created_at ASC
LIMIT 1
`

type GetAnyMembershipByUserIDRow struct {
	OrgID  uuid.UUID `json:"org_id"`
	UserID uuid.UUID `json:"user_id"`
	Role   string    `json:"role"`
}

func (q *Queries) GetAnyMembershipByUserID(ctx context.Context, userID uuid.UUID) (GetAnyMembershipByUserIDRow, error) {
	row := q.db.QueryRowContext(ctx, getAnyMembershipByUserID, userID)
	var i GetAnyMembershipByUserIDRow
	err := row.Scan(&i.OrgID, &i.UserID, &i.Role)
	return i, err
}

const getMembershipByOrgAndUserID = `-- name: GetMembershipByOrgAndUserID :one
SELECT org_id, user_id, role
FROM public.memberships
WHERE org_id = $1 AND user_id = $2
`

type GetMembershipByOrgAndUserIDParams struct {
	OrgID  uuid.UUID `json:"org_id"`
	UserID uuid.UUID `json:"user_id"`
}

type GetMembershipByOrgAndUserIDRow struct {
	OrgID  uuid.UUID `json:"org_id"`
	UserID uuid.UUID `json:"user_id"`
	Role   string    `json:"role"`
}

func (q *Queries) GetMembershipByOrgAndUserID(ctx context.Context, arg GetMembershipByOrgAndUserIDParams) (GetMembershipByOrgAndUserIDRow, error) {
	row := q.db.QueryRowContext(ctx, getMembershipByOrgAndUserID, arg.OrgID, arg.UserID)
	var i GetMembershipByOrgAndUserIDRow
	err := row.Scan(&i.OrgID, &i.UserID, &i.Role)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, oidc_issuer, oidc_sub, email, name, created_at, updated_at
FROM public.users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OidcIssuer,
		&i.OidcSub,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasPermission = `-- name: HasPermission :one
SELECT EXISTS(
  SELECT 1
  FROM public.role_permissions rp
  WHERE rp.role = $1
    AND rp.permission_id = $2
) AS has_permission
`

type HasPermissionParams struct {
	Role         string `json:"role"`
	PermissionID string `json:"permission_id"`
}

func (q *Queries) HasPermission(ctx context.Context, arg HasPermissionParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasPermission, arg.Role, arg.PermissionID)
	var has_permission bool
	err := row.Scan(&has_permission)
	return has_permission, err
}

const listPermissionsByRole = `-- name: ListPermissionsByRole :many
SELECT p.id, p.description, p.created_at
FROM public.permissions p
INNER JOIN public.role_permissions rp ON rp.permission_id = p.id
WHERE rp.role = $1
ORDER BY p.id
`

func (q *Queries) ListPermissionsByRole(ctx context.Context, role string) ([]Permission, error) {
	rows, err := q.db.QueryContext(ctx, listPermissionsByRole, role)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(&i.ID, &i.Description, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMembership = `-- name: UpsertMembership :one
INSERT INTO public.memberships (org_id, user_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (org_id, user_id) DO UPDATE
SET role = EXCLUDED.role,
    updated_at = now()
RETURNING org_id, user_id, role
`

type UpsertMembershipParams struct {
	OrgID  uuid.UUID `json:"org_id"`
	UserID uuid.UUID `json:"user_id"`
	Role   string    `json:"role"`
}

type UpsertMembershipRow struct {
	OrgID  uuid.UUID `json:"org_id"`
	UserID uuid.UUID `json:"user_id"`
	Role   string    `json:"role"`
}

func (q *Queries) UpsertMembership(ctx context.Context, arg UpsertMembershipParams) (UpsertMembershipRow, error) {
	row := q.db.QueryRowContext(ctx, upsertMembership, arg.OrgID, arg.UserID, arg.Role)
	var i UpsertMembershipRow
	err := row.Scan(&i.OrgID, &i.UserID, &i.Role)
	return i, err
}

const upsertUserFromOIDC = `-- name: UpsertUserFromOIDC :one

INSERT INTO public.users (oidc_issuer, oidc_sub, email, name)
VALUES ($1, $2, $3, $4)
ON CONFLICT (oidc_issuer, oidc_sub) DO UPDATE
SET email = EXCLUDED.email,
    name = EXCLUDED.name,
    updated_at = now()
RETURNING id, oidc_issuer, oidc_sub, email, name
`

type UpsertUserFromOIDCParams struct {
	OidcIssuer string `json:"oidc_issuer"`
	OidcSub    string `json:"oidc_sub"`
	Email      string `json:"email"`
	Name       string `json:"name"`
}

type UpsertUserFromOIDCRow struct {
	ID         uuid.UUID `json:"id"`
	OidcIssuer string    `json:"oidc_issuer"`
	OidcSub    string    `json:"oidc_sub"`
	Email      string    `json:"email"`
	Name       string    `json:"name"`
}

// MVP-011: RBAC (organizations/users/memberships)
func (q *Queries) UpsertUserFromOIDC(ctx context.Context, arg UpsertUserFromOIDCParams) (UpsertUserFromOIDCRow, error) {
	row := q.db.QueryRowContext(ctx, upsertUserFromOIDC,
		arg.OidcIssuer,
		arg.OidcSub,
		arg.Email,
		arg.Name,
	)
	var i UpsertUserFromOIDCRow
	err := row.Scan(
		&i.ID,
		&i.OidcIssuer,
		&i.OidcSub,
		&i.Email,
		&i.Name,
	)
	return i, err
}
