// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: requests.sql

package dbgen

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const getRequestByOrgAndID = `-- name: GetRequestByOrgAndID :one
SELECT id, org_id, title, status, created_by_user_id, decided_by_user_id, created_at, updated_at, submitted_at, decided_at
FROM public.requests
WHERE org_id = $1 AND id = $2
`

type GetRequestByOrgAndIDParams struct {
	OrgID uuid.UUID `json:"org_id"`
	ID    uuid.UUID `json:"id"`
}

func (q *Queries) GetRequestByOrgAndID(ctx context.Context, arg GetRequestByOrgAndIDParams) (Request, error) {
	row := q.db.QueryRowContext(ctx, getRequestByOrgAndID, arg.OrgID, arg.ID)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Title,
		&i.Status,
		&i.CreatedByUserID,
		&i.DecidedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SubmittedAt,
		&i.DecidedAt,
	)
	return i, err
}

const listRequestAuditTrail = `-- name: ListRequestAuditTrail :many
SELECT id, org_id, request_id, actor_user_id, action, data, occurred_at
FROM public.request_audit_trail
WHERE org_id = $1 AND request_id = $2
ORDER BY occurred_at ASC
`

type ListRequestAuditTrailParams struct {
	OrgID     uuid.UUID `json:"org_id"`
	RequestID uuid.UUID `json:"request_id"`
}

type ListRequestAuditTrailRow struct {
	ID          uuid.UUID       `json:"id"`
	OrgID       uuid.UUID       `json:"org_id"`
	RequestID   uuid.UUID       `json:"request_id"`
	ActorUserID uuid.NullUUID   `json:"actor_user_id"`
	Action      string          `json:"action"`
	Data        json.RawMessage `json:"data"`
	OccurredAt  time.Time       `json:"occurred_at"`
}

func (q *Queries) ListRequestAuditTrail(ctx context.Context, arg ListRequestAuditTrailParams) ([]ListRequestAuditTrailRow, error) {
	rows, err := q.db.QueryContext(ctx, listRequestAuditTrail, arg.OrgID, arg.RequestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRequestAuditTrailRow{}
	for rows.Next() {
		var i ListRequestAuditTrailRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.RequestID,
			&i.ActorUserID,
			&i.Action,
			&i.Data,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestSteps = `-- name: ListRequestSteps :many
SELECT request_id, step_index, label, status, assigned_to_user_id, updated_at
FROM public.request_steps
WHERE request_id = $1
ORDER BY step_index ASC
`

func (q *Queries) ListRequestSteps(ctx context.Context, requestID uuid.UUID) ([]RequestStep, error) {
	rows, err := q.db.QueryContext(ctx, listRequestSteps, requestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RequestStep{}
	for rows.Next() {
		var i RequestStep
		if err := rows.Scan(
			&i.RequestID,
			&i.StepIndex,
			&i.Label,
			&i.Status,
			&i.AssignedToUserID,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestsByOrg = `-- name: ListRequestsByOrg :many

SELECT id, org_id, title, status, created_by_user_id, decided_by_user_id, created_at, updated_at, submitted_at, decided_at
FROM public.requests
WHERE org_id = $1
ORDER BY created_at DESC
LIMIT $2
OFFSET $3
`

type ListRequestsByOrgParams struct {
	OrgID  uuid.UUID `json:"org_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

// MVP-030: Read Model queries for requests
func (q *Queries) ListRequestsByOrg(ctx context.Context, arg ListRequestsByOrgParams) ([]Request, error) {
	rows, err := q.db.QueryContext(ctx, listRequestsByOrg, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Request{}
	for rows.Next() {
		var i Request
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Title,
			&i.Status,
			&i.CreatedByUserID,
			&i.DecidedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SubmittedAt,
			&i.DecidedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchRequests = `-- name: SearchRequests :many
SELECT id, org_id, title, status, created_by_user_id, decided_by_user_id, created_at, updated_at, submitted_at, decided_at
FROM public.requests
WHERE org_id = $1
  AND ($2::text IS NULL OR title ILIKE '%' || $2::text || '%')
  AND ($3::text IS NULL OR status = $3::text)
  AND ($4::timestamptz IS NULL OR created_at >= $4::timestamptz)
  AND ($5::timestamptz IS NULL OR created_at <= $5::timestamptz)
ORDER BY created_at DESC
LIMIT $7
OFFSET $6
`

type SearchRequestsParams struct {
	OrgID          uuid.UUID      `json:"org_id"`
	Title          sql.NullString `json:"title"`
	Status         sql.NullString `json:"status"`
	CreatedAtStart sql.NullTime   `json:"created_at_start"`
	CreatedAtEnd   sql.NullTime   `json:"created_at_end"`
	OffsetCount    int32          `json:"offset_count"`
	LimitCount     int32          `json:"limit_count"`
}

func (q *Queries) SearchRequests(ctx context.Context, arg SearchRequestsParams) ([]Request, error) {
	rows, err := q.db.QueryContext(ctx, searchRequests,
		arg.OrgID,
		arg.Title,
		arg.Status,
		arg.CreatedAtStart,
		arg.CreatedAtEnd,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Request{}
	for rows.Next() {
		var i Request
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Title,
			&i.Status,
			&i.CreatedByUserID,
			&i.DecidedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SubmittedAt,
			&i.DecidedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
