// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: request_projector.sql

package dbgen

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const insertRequestAuditIfNotExists = `-- name: InsertRequestAuditIfNotExists :exec
INSERT INTO public.request_audit_trail (
  org_id,
  request_id,
  actor_user_id,
  action,
  data,
  occurred_at,
  event_global_position
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (org_id, event_global_position) DO NOTHING
`

type InsertRequestAuditIfNotExistsParams struct {
	OrgID               uuid.UUID       `json:"org_id"`
	RequestID           uuid.UUID       `json:"request_id"`
	ActorUserID         uuid.NullUUID   `json:"actor_user_id"`
	Action              string          `json:"action"`
	Data                json.RawMessage `json:"data"`
	OccurredAt          time.Time       `json:"occurred_at"`
	EventGlobalPosition sql.NullInt64   `json:"event_global_position"`
}

func (q *Queries) InsertRequestAuditIfNotExists(ctx context.Context, arg InsertRequestAuditIfNotExistsParams) error {
	_, err := q.db.ExecContext(ctx, insertRequestAuditIfNotExists,
		arg.OrgID,
		arg.RequestID,
		arg.ActorUserID,
		arg.Action,
		arg.Data,
		arg.OccurredAt,
		arg.EventGlobalPosition,
	)
	return err
}

const insertRequestIfNotExists = `-- name: InsertRequestIfNotExists :exec

INSERT INTO public.requests (
  id,
  org_id,
  title,
  status,
  created_by_user_id,
  created_at,
  updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $6)
ON CONFLICT (id) DO NOTHING
`

type InsertRequestIfNotExistsParams struct {
	ID              uuid.UUID     `json:"id"`
	OrgID           uuid.UUID     `json:"org_id"`
	Title           string        `json:"title"`
	Status          string        `json:"status"`
	CreatedByUserID uuid.NullUUID `json:"created_by_user_id"`
	CreatedAt       time.Time     `json:"created_at"`
}

// MVP-032: projector queries for requests read model
func (q *Queries) InsertRequestIfNotExists(ctx context.Context, arg InsertRequestIfNotExistsParams) error {
	_, err := q.db.ExecContext(ctx, insertRequestIfNotExists,
		arg.ID,
		arg.OrgID,
		arg.Title,
		arg.Status,
		arg.CreatedByUserID,
		arg.CreatedAt,
	)
	return err
}

const insertRequestStepIfNotExists = `-- name: InsertRequestStepIfNotExists :exec
INSERT INTO public.request_steps (
  request_id,
  step_index,
  label,
  status,
  assigned_to_user_id,
  updated_at
)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (request_id, step_index) DO NOTHING
`

type InsertRequestStepIfNotExistsParams struct {
	RequestID        uuid.UUID     `json:"request_id"`
	StepIndex        int32         `json:"step_index"`
	Label            string        `json:"label"`
	Status           string        `json:"status"`
	AssignedToUserID uuid.NullUUID `json:"assigned_to_user_id"`
	UpdatedAt        time.Time     `json:"updated_at"`
}

func (q *Queries) InsertRequestStepIfNotExists(ctx context.Context, arg InsertRequestStepIfNotExistsParams) error {
	_, err := q.db.ExecContext(ctx, insertRequestStepIfNotExists,
		arg.RequestID,
		arg.StepIndex,
		arg.Label,
		arg.Status,
		arg.AssignedToUserID,
		arg.UpdatedAt,
	)
	return err
}

const setRequestApproved = `-- name: SetRequestApproved :execrows
UPDATE public.requests
SET status = 'approved',
    decided_at = $3,
    updated_at = $3
WHERE org_id = $1 AND id = $2
`

type SetRequestApprovedParams struct {
	OrgID     uuid.UUID    `json:"org_id"`
	ID        uuid.UUID    `json:"id"`
	DecidedAt sql.NullTime `json:"decided_at"`
}

func (q *Queries) SetRequestApproved(ctx context.Context, arg SetRequestApprovedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setRequestApproved, arg.OrgID, arg.ID, arg.DecidedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setRequestRejected = `-- name: SetRequestRejected :execrows
UPDATE public.requests
SET status = 'rejected',
    decided_at = $3,
    updated_at = $3
WHERE org_id = $1 AND id = $2
`

type SetRequestRejectedParams struct {
	OrgID     uuid.UUID    `json:"org_id"`
	ID        uuid.UUID    `json:"id"`
	DecidedAt sql.NullTime `json:"decided_at"`
}

func (q *Queries) SetRequestRejected(ctx context.Context, arg SetRequestRejectedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setRequestRejected, arg.OrgID, arg.ID, arg.DecidedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setRequestSubmitted = `-- name: SetRequestSubmitted :execrows
UPDATE public.requests
SET status = 'submitted',
    submitted_at = $3,
    updated_at = $3
WHERE org_id = $1 AND id = $2
`

type SetRequestSubmittedParams struct {
	OrgID       uuid.UUID    `json:"org_id"`
	ID          uuid.UUID    `json:"id"`
	SubmittedAt sql.NullTime `json:"submitted_at"`
}

func (q *Queries) SetRequestSubmitted(ctx context.Context, arg SetRequestSubmittedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setRequestSubmitted, arg.OrgID, arg.ID, arg.SubmittedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
