// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: smoketest.sql

package dbgen

import (
	"context"
)

const getMigrationSmoketest = `-- name: GetMigrationSmoketest :one
SELECT id, created_at
FROM public._ponsu_migrations_smoketest
WHERE id = $1
`

func (q *Queries) GetMigrationSmoketest(ctx context.Context, id int32) (PonsuMigrationsSmoketest, error) {
	row := q.db.QueryRowContext(ctx, getMigrationSmoketest, id)
	var i PonsuMigrationsSmoketest
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const ping = `-- name: Ping :one

SELECT 1::int AS one
`

// MVP-004: sqlc smoke test queries
//
// NOTE: Uses the MVP-003 migration table.
func (q *Queries) Ping(ctx context.Context) (int32, error) {
	row := q.db.QueryRowContext(ctx, ping)
	var one int32
	err := row.Scan(&one)
	return one, err
}

const upsertMigrationSmoketest = `-- name: UpsertMigrationSmoketest :one
INSERT INTO public._ponsu_migrations_smoketest (id)
VALUES ($1)
ON CONFLICT (id) DO UPDATE
SET created_at = now()
RETURNING id, created_at
`

func (q *Queries) UpsertMigrationSmoketest(ctx context.Context, id int32) (PonsuMigrationsSmoketest, error) {
	row := q.db.QueryRowContext(ctx, upsertMigrationSmoketest, id)
	var i PonsuMigrationsSmoketest
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}
