// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_stats.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const upsertUserStatsOnRequestCreated = `-- name: UpsertUserStatsOnRequestCreated :exec
INSERT INTO public.user_stats (
  user_id,
  request_count,
  last_request_at
)
VALUES (
  $1, -- user_id
  $2, -- increment_by
  $3  -- occurred_at
)
ON CONFLICT (user_id) DO UPDATE
SET
  request_count = public.user_stats.request_count + EXCLUDED.request_count,
  last_request_at = GREATEST(public.user_stats.last_request_at, EXCLUDED.last_request_at)
`

type UpsertUserStatsOnRequestCreatedParams struct {
	UserID        uuid.UUID `json:"user_id"`
	RequestCount  int64     `json:"request_count"`
	LastRequestAt time.Time `json:"last_request_at"`
}

func (q *Queries) UpsertUserStatsOnRequestCreated(ctx context.Context, arg UpsertUserStatsOnRequestCreatedParams) error {
	_, err := q.db.ExecContext(ctx, upsertUserStatsOnRequestCreated, arg.UserID, arg.RequestCount, arg.LastRequestAt)
	return err
}
