// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workflow_templates.sql

package dbgen

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createWorkflowTemplate = `-- name: CreateWorkflowTemplate :one

INSERT INTO public.workflow_templates (
  org_id,
  name,
  description,
  definition,
  created_by_user_id
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, org_id, name, description, definition, created_by_user_id, created_at, updated_at
`

type CreateWorkflowTemplateParams struct {
	OrgID           uuid.UUID       `json:"org_id"`
	Name            string          `json:"name"`
	Description     string          `json:"description"`
	Definition      json.RawMessage `json:"definition"`
	CreatedByUserID uuid.NullUUID   `json:"created_by_user_id"`
}

// MVP-040: Read Model queries for workflow templates
func (q *Queries) CreateWorkflowTemplate(ctx context.Context, arg CreateWorkflowTemplateParams) (WorkflowTemplate, error) {
	row := q.db.QueryRowContext(ctx, createWorkflowTemplate,
		arg.OrgID,
		arg.Name,
		arg.Description,
		arg.Definition,
		arg.CreatedByUserID,
	)
	var i WorkflowTemplate
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Description,
		&i.Definition,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkflowTemplateByOrgAndID = `-- name: GetWorkflowTemplateByOrgAndID :one
SELECT id, org_id, name, description, definition, created_by_user_id, created_at, updated_at
FROM public.workflow_templates
WHERE org_id = $1 AND id = $2
`

type GetWorkflowTemplateByOrgAndIDParams struct {
	OrgID uuid.UUID `json:"org_id"`
	ID    uuid.UUID `json:"id"`
}

func (q *Queries) GetWorkflowTemplateByOrgAndID(ctx context.Context, arg GetWorkflowTemplateByOrgAndIDParams) (WorkflowTemplate, error) {
	row := q.db.QueryRowContext(ctx, getWorkflowTemplateByOrgAndID, arg.OrgID, arg.ID)
	var i WorkflowTemplate
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Description,
		&i.Definition,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWorkflowTemplatesByOrg = `-- name: ListWorkflowTemplatesByOrg :many
SELECT id, org_id, name, description, definition, created_by_user_id, created_at, updated_at
FROM public.workflow_templates
WHERE org_id = $1
ORDER BY created_at DESC
LIMIT $2
OFFSET $3
`

type ListWorkflowTemplatesByOrgParams struct {
	OrgID  uuid.UUID `json:"org_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListWorkflowTemplatesByOrg(ctx context.Context, arg ListWorkflowTemplatesByOrgParams) ([]WorkflowTemplate, error) {
	rows, err := q.db.QueryContext(ctx, listWorkflowTemplatesByOrg, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkflowTemplate{}
	for rows.Next() {
		var i WorkflowTemplate
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Description,
			&i.Definition,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
