package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"
	"errors"

	"github.com/morimasaki-web/ponsu/internal/interface/graphql/graph/generated"
	"github.com/morimasaki-web/ponsu/internal/interface/graphql/graph/model"
	"github.com/morimasaki-web/ponsu/internal/interface/graphqlctx"
)

// Ping is the resolver for the ping field.
func (r *queryResolver) Ping(ctx context.Context) (string, error) {
	return "pong", nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.Me, error) {
	v, ok := graphqlctx.ViewerFrom(ctx)
	if !ok {
		return nil, errors.New("unauthorized")
	}

	var name *string
	if v.Name != "" {
		name = &v.Name
	}
	var email *string
	if v.Email != "" {
		email = &v.Email
	}

	return &model.Me{
		UserID: v.UserID.String(),
		OrgID:  v.OrgID.String(),
		Role:   v.Role,
		Name:   name,
		Email:  email,
	}, nil
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
