package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/morimasaki-web/ponsu/internal/infrastructure/dbgen"
	"github.com/morimasaki-web/ponsu/internal/interface/graphql/graph/generated"
	"github.com/morimasaki-web/ponsu/internal/interface/graphql/graph/model"
	attachmentsuc "github.com/morimasaki-web/ponsu/internal/usecase/attachments"
	requestsuc "github.com/morimasaki-web/ponsu/internal/usecase/requests"
)

// CreateRequest is the resolver for the createRequest field.
func (r *mutationResolver) CreateRequest(ctx context.Context, title string, workflowTemplateID *string) (*model.Request, error) {
	v, err := viewerFromContext(ctx)
	if err != nil {
		return nil, err
	}
	q, err := r.queries()
	if err != nil {
		return nil, err
	}

	workflowTemplateUUID := uuid.Nil
	if workflowTemplateID != nil && *workflowTemplateID != "" {
		uid, err := parseUUID(*workflowTemplateID)
		if err != nil {
			return nil, err
		}
		workflowTemplateUUID = uid
	}

	svc := requestsuc.Service{DB: r.DB, Notifier: r.RequestsNotifier, PublicBaseURL: r.PublicBaseURL, ActorDisplay: actorDisplayFromViewer(v)}
	requestID, err := svc.CreateRequestWithTemplate(ctx, v.OrgID, v.UserID, title, workflowTemplateUUID)
	if err != nil {
		return nil, err
	}

	row, err := q.GetRequestByOrgAndID(ctx, dbgen.GetRequestByOrgAndIDParams{OrgID: v.OrgID, ID: requestID})
	if err != nil {
		return nil, err
	}
	out := mapRequestRow(row)
	return out, nil
}

// SubmitRequest is the resolver for the submitRequest field.
func (r *mutationResolver) SubmitRequest(ctx context.Context, id string) (*model.Request, error) {
	v, err := viewerFromContext(ctx)
	if err != nil {
		return nil, err
	}
	q, err := r.queries()
	if err != nil {
		return nil, err
	}
	requestID, err := parseUUID(id)
	if err != nil {
		return nil, err
	}

	svc := requestsuc.Service{DB: r.DB, Notifier: r.RequestsNotifier, PublicBaseURL: r.PublicBaseURL, ActorDisplay: actorDisplayFromViewer(v)}
	if err := svc.SubmitRequest(ctx, v.OrgID, v.UserID, requestID); err != nil {
		return nil, err
	}

	row, err := q.GetRequestByOrgAndID(ctx, dbgen.GetRequestByOrgAndIDParams{OrgID: v.OrgID, ID: requestID})
	if err != nil {
		return nil, err
	}
	return mapRequestRow(row), nil
}

// ApproveRequest is the resolver for the approveRequest field.
func (r *mutationResolver) ApproveRequest(ctx context.Context, id string) (*model.Request, error) {
	v, err := viewerFromContext(ctx)
	if err != nil {
		return nil, err
	}
	q, err := r.queries()
	if err != nil {
		return nil, err
	}
	requestID, err := parseUUID(id)
	if err != nil {
		return nil, err
	}

	svc := requestsuc.Service{DB: r.DB, Notifier: r.RequestsNotifier, PublicBaseURL: r.PublicBaseURL, ActorDisplay: actorDisplayFromViewer(v)}
	if err := svc.ApproveRequest(ctx, v.OrgID, v.UserID, requestID); err != nil {
		return nil, err
	}

	row, err := q.GetRequestByOrgAndID(ctx, dbgen.GetRequestByOrgAndIDParams{OrgID: v.OrgID, ID: requestID})
	if err != nil {
		return nil, err
	}
	return mapRequestRow(row), nil
}

// RejectRequest is the resolver for the rejectRequest field.
func (r *mutationResolver) RejectRequest(ctx context.Context, id string, reason string) (*model.Request, error) {
	v, err := viewerFromContext(ctx)
	if err != nil {
		return nil, err
	}
	q, err := r.queries()
	if err != nil {
		return nil, err
	}
	requestID, err := parseUUID(id)
	if err != nil {
		return nil, err
	}

	svc := requestsuc.Service{DB: r.DB, Notifier: r.RequestsNotifier, PublicBaseURL: r.PublicBaseURL, ActorDisplay: actorDisplayFromViewer(v)}
	if err := svc.RejectRequest(ctx, v.OrgID, v.UserID, requestID, reason); err != nil {
		return nil, err
	}

	row, err := q.GetRequestByOrgAndID(ctx, dbgen.GetRequestByOrgAndIDParams{OrgID: v.OrgID, ID: requestID})
	if err != nil {
		return nil, err
	}
	return mapRequestRow(row), nil
}

// ReturnRequest is the resolver for the returnRequest field.
func (r *mutationResolver) ReturnRequest(ctx context.Context, id string, reason string) (*model.Request, error) {
	v, err := viewerFromContext(ctx)
	if err != nil {
		return nil, err
	}
	q, err := r.queries()
	if err != nil {
		return nil, err
	}
	requestID, err := parseUUID(id)
	if err != nil {
		return nil, err
	}

	svc := requestsuc.Service{DB: r.DB, Notifier: r.RequestsNotifier, PublicBaseURL: r.PublicBaseURL, ActorDisplay: actorDisplayFromViewer(v)}
	if err := svc.ReturnRequest(ctx, v.OrgID, v.UserID, requestID, reason); err != nil {
		return nil, err
	}

	row, err := q.GetRequestByOrgAndID(ctx, dbgen.GetRequestByOrgAndIDParams{OrgID: v.OrgID, ID: requestID})
	if err != nil {
		return nil, err
	}
	return mapRequestRow(row), nil
}

// ResubmitRequest is the resolver for the resubmitRequest field.
func (r *mutationResolver) ResubmitRequest(ctx context.Context, id string) (*model.Request, error) {
	v, err := viewerFromContext(ctx)
	if err != nil {
		return nil, err
	}
	q, err := r.queries()
	if err != nil {
		return nil, err
	}
	requestID, err := parseUUID(id)
	if err != nil {
		return nil, err
	}

	svc := requestsuc.Service{DB: r.DB, Notifier: r.RequestsNotifier, PublicBaseURL: r.PublicBaseURL, ActorDisplay: actorDisplayFromViewer(v)}
	if err := svc.ResubmitRequest(ctx, v.OrgID, v.UserID, requestID); err != nil {
		return nil, err
	}

	row, err := q.GetRequestByOrgAndID(ctx, dbgen.GetRequestByOrgAndIDParams{OrgID: v.OrgID, ID: requestID})
	if err != nil {
		return nil, err
	}
	return mapRequestRow(row), nil
}

// AddComment is the resolver for the addComment field.
func (r *mutationResolver) AddComment(ctx context.Context, requestID string, content string) (*model.Comment, error) {
	v, err := viewerFromContext(ctx)
	if err != nil {
		return nil, err
	}
	q, err := r.queries()
	if err != nil {
		return nil, err
	}
	reqID, err := parseUUID(requestID)
	if err != nil {
		return nil, err
	}

	svc := requestsuc.Service{DB: r.DB, Notifier: r.RequestsNotifier, PublicBaseURL: r.PublicBaseURL, ActorDisplay: actorDisplayFromViewer(v)}
	commentID, err := svc.AddComment(ctx, v.OrgID, v.UserID, reqID, content)
	if err != nil {
		return nil, err
	}

	comments, err := q.ListCommentsByRequest(ctx, dbgen.ListCommentsByRequestParams{
		OrgID:     v.OrgID,
		RequestID: reqID,
	})
	if err != nil {
		return nil, err
	}

	for _, c := range comments {
		if c.ID == commentID {
			return &model.Comment{
				ID:        c.ID.String(),
				RequestID: c.RequestID.String(),
				UserID:    c.UserID.String(),
				Content:   c.Content,
				CreatedAt: c.CreatedAt,
			}, nil
		}
	}

	return nil, errors.New("comment not found after insert")
}

// CreateWorkflowTemplate is the resolver for the createWorkflowTemplate field.
func (r *mutationResolver) CreateWorkflowTemplate(ctx context.Context, name string, description string, definition map[string]any) (*model.WorkflowTemplate, error) {
	v, err := viewerFromContext(ctx)
	if err != nil {
		return nil, err
	}
	q, err := r.queries()
	if err != nil {
		return nil, err
	}

	mem, err := q.GetMembershipByOrgAndUserID(ctx, dbgen.GetMembershipByOrgAndUserIDParams{OrgID: v.OrgID, UserID: v.UserID})
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, errForbidden
		}
		return nil, err
	}
	if mem.Role != "admin" {
		return nil, errForbidden
	}

	defBytes, err := json.Marshal(definition)
	if err != nil {
		return nil, errors.New("invalid definition")
	}

	row, err := q.CreateWorkflowTemplate(ctx, dbgen.CreateWorkflowTemplateParams{
		OrgID:       v.OrgID,
		Name:        name,
		Description: description,
		Definition:  defBytes,
		CreatedByUserID: uuid.NullUUID{
			UUID:  v.UserID,
			Valid: true,
		},
	})
	if err != nil {
		return nil, err
	}
	return mapWorkflowTemplateRow(row)
}

// Ping is the resolver for the ping field.
func (r *queryResolver) Ping(ctx context.Context) (string, error) {
	return "pong", nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.Me, error) {
	v, err := viewerFromContext(ctx)
	if err != nil {
		return nil, err
	}

	var name *string
	if v.Name != "" {
		name = &v.Name
	}
	var email *string
	if v.Email != "" {
		email = &v.Email
	}

	return &model.Me{
		UserID: v.UserID.String(),
		OrgID:  v.OrgID.String(),
		Role:   v.Role,
		Name:   name,
		Email:  email,
	}, nil
}

// Requests is the resolver for the requests field.
func (r *queryResolver) Requests(ctx context.Context, limit *int, offset *int) ([]*model.Request, error) {
	v, err := viewerFromContext(ctx)
	if err != nil {
		return nil, err
	}
	q, err := r.queries()
	if err != nil {
		return nil, err
	}

	lim := int32(50)
	off := int32(0)
	if limit != nil {
		lim = int32(*limit)
	}
	if offset != nil {
		off = int32(*offset)
	}
	items, err := q.ListRequestsByOrg(ctx, dbgen.ListRequestsByOrgParams{OrgID: v.OrgID, Limit: lim, Offset: off})
	if err != nil {
		return nil, err
	}
	out := make([]*model.Request, 0, len(items))
	for _, it := range items {
		out = append(out, mapRequestRow(it))
	}
	return out, nil
}

// Request is the resolver for the request field.
func (r *queryResolver) Request(ctx context.Context, id string) (*model.Request, error) {
	v, err := viewerFromContext(ctx)
	if err != nil {
		return nil, err
	}
	q, err := r.queries()
	if err != nil {
		return nil, err
	}
	requestID, err := parseUUID(id)
	if err != nil {
		return nil, err
	}
	row, err := q.GetRequestByOrgAndID(ctx, dbgen.GetRequestByOrgAndIDParams{OrgID: v.OrgID, ID: requestID})
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, nil
		}
		return nil, err
	}

	out := mapRequestRow(row)

	steps, err := q.ListRequestSteps(ctx, requestID)
	if err != nil {
		return nil, err
	}
	out.Steps = mapRequestSteps(steps)

	auditRows, err := q.ListRequestAuditTrail(ctx, dbgen.ListRequestAuditTrailParams{OrgID: v.OrgID, RequestID: requestID})
	if err != nil {
		return nil, err
	}
	audit, err := mapAuditTrail(auditRows)
	if err != nil {
		return nil, err
	}
	out.AuditTrail = audit

	return out, nil
}

// SearchRequests is the resolver for the searchRequests field.
func (r *queryResolver) SearchRequests(ctx context.Context, title *string, status *string, createdAtStart *time.Time, createdAtEnd *time.Time, limit *int, offset *int) ([]*model.Request, error) {
	v, err := viewerFromContext(ctx)
	if err != nil {
		return nil, err
	}
	q, err := r.queries()
	if err != nil {
		return nil, err
	}

	// デフォルト値の設定
	actualLimit := int32(50)
	if limit != nil {
		actualLimit = int32(*limit)
	}
	actualOffset := int32(0)
	if offset != nil {
		actualOffset = int32(*offset)
	}

	// NULLable型への変換
	var titleParam, statusParam sql.NullString
	var startParam, endParam sql.NullTime

	if title != nil {
		titleParam = sql.NullString{String: *title, Valid: true}
	}
	if status != nil {
		statusParam = sql.NullString{String: *status, Valid: true}
	}
	if createdAtStart != nil {
		startParam = sql.NullTime{Time: *createdAtStart, Valid: true}
	}
	if createdAtEnd != nil {
		endParam = sql.NullTime{Time: *createdAtEnd, Valid: true}
	}

	// SQLクエリ実行
	rows, err := q.SearchRequests(ctx, dbgen.SearchRequestsParams{
		OrgID:          v.OrgID,
		Title:          titleParam,
		Status:         statusParam,
		CreatedAtStart: startParam,
		CreatedAtEnd:   endParam,
		LimitCount:     actualLimit,
		OffsetCount:    actualOffset,
	})
	if err != nil {
		return nil, err
	}

	// GraphQL型に変換
	var out []*model.Request
	for _, row := range rows {
		out = append(out, mapRequestRow(row))
	}

	return out, nil
}

// Comments is the resolver for the comments field.
func (r *queryResolver) Comments(ctx context.Context, requestID string) ([]*model.Comment, error) {
	v, err := viewerFromContext(ctx)
	if err != nil {
		return nil, err
	}
	q, err := r.queries()
	if err != nil {
		return nil, err
	}
	reqID, err := parseUUID(requestID)
	if err != nil {
		return nil, err
	}
	rows, err := q.ListCommentsByRequest(ctx, dbgen.ListCommentsByRequestParams{
		OrgID:     v.OrgID,
		RequestID: reqID,
	})
	if err != nil {
		return nil, err
	}
	var out []*model.Comment
	for _, r := range rows {
		out = append(out, &model.Comment{
			ID:        r.ID.String(),
			RequestID: r.RequestID.String(),
			UserID:    r.UserID.String(),
			Content:   r.Content,
			CreatedAt: r.CreatedAt,
		})
	}
	return out, nil
}

// WorkflowTemplates is the resolver for the workflowTemplates field.
func (r *queryResolver) WorkflowTemplates(ctx context.Context, limit *int, offset *int) ([]*model.WorkflowTemplate, error) {
	v, err := viewerFromContext(ctx)
	if err != nil {
		return nil, err
	}
	q, err := r.queries()
	if err != nil {
		return nil, err
	}

	lim := int32(50)
	off := int32(0)
	if limit != nil {
		lim = int32(*limit)
	}
	if offset != nil {
		off = int32(*offset)
	}
	items, err := q.ListWorkflowTemplatesByOrg(ctx, dbgen.ListWorkflowTemplatesByOrgParams{OrgID: v.OrgID, Limit: lim, Offset: off})
	if err != nil {
		return nil, err
	}

	out := make([]*model.WorkflowTemplate, 0, len(items))
	for _, it := range items {
		m, err := mapWorkflowTemplateRow(it)
		if err != nil {
			return nil, err
		}
		out = append(out, m)
	}
	return out, nil
}

// AvgTimeToApproval is the resolver for the avgTimeToApproval field.
func (r *queryResolver) AvgTimeToApproval(ctx context.Context) (*model.AvgTimeToApprovalResult, error) {
	v, err := viewerFromContext(ctx)
	if err != nil {
		return nil, err
	}
	q, err := r.queries()
	if err != nil {
		return nil, err
	}

	row, err := q.AvgTimeToApproval(ctx, v.OrgID)
	if err != nil {
		return nil, err
	}

	return &model.AvgTimeToApprovalResult{
		AvgSeconds:  row.AvgSeconds,
		SampleCount: int(row.SampleCount),
	}, nil
}

// CountRequestsByMonth is the resolver for the countRequestsByMonth field.
func (r *queryResolver) CountRequestsByMonth(ctx context.Context, startDate *time.Time, endDate *time.Time) ([]*model.CountRequestsByMonthRow, error) {
	v, err := viewerFromContext(ctx)
	if err != nil {
		return nil, err
	}
	q, err := r.queries()
	if err != nil {
		return nil, err
	}

	params := dbgen.CountRequestsByMonthParams{
		OrgID: v.OrgID,
	}
	if startDate != nil {
		params.StartDate = sql.NullTime{Time: *startDate, Valid: true}
	}
	if endDate != nil {
		params.EndDate = sql.NullTime{Time: *endDate, Valid: true}
	}

	row, err := q.CountRequestsByMonth(ctx, params)
	if err != nil {
		return nil, err
	}

	var out []*model.CountRequestsByMonthRow
	for _, r := range row {
		out = append(out, &model.CountRequestsByMonthRow{
			Month: r.Month,
			Count: int(r.Count),
		})
	}
	return out, nil
}

// CountRequestsByStatus is the resolver for the countRequestsByStatus field.
func (r *queryResolver) CountRequestsByStatus(ctx context.Context) ([]*model.CountRequestsByStatusRow, error) {
	v, err := viewerFromContext(ctx)
	if err != nil {
		return nil, err
	}
	q, err := r.queries()
	if err != nil {
		return nil, err
	}

	rows, err := q.CountRequestsByStatus(ctx, v.OrgID)
	if err != nil {
		return nil, err
	}

	var out []*model.CountRequestsByStatusRow
	for _, r := range rows {
		out = append(out, &model.CountRequestsByStatusRow{
			Status: r.Status,
			Count:  int(r.Count),
		})
	}
	return out, nil
}

// DashboardSummary is the resolver for the dashboardSummary field.
func (r *queryResolver) DashboardSummary(ctx context.Context) (*model.DashboardSummaryResult, error) {
	v, err := viewerFromContext(ctx)
	if err != nil {
		return nil, err
	}
	q, err := r.queries()
	if err != nil {
		return nil, err
	}

	row, err := q.GetDashboardSummary(ctx, v.OrgID)
	if err != nil {
		return nil, err
	}

	return &model.DashboardSummaryResult{
		DraftCount:         int(row.DraftCount),
		SubmittedCount:     int(row.SubmittedCount),
		ApprovedCount:      int(row.ApprovedCount),
		RejectedCount:      int(row.RejectedCount),
		TotalCount:         int(row.TotalCount),
		AvgApprovalSeconds: row.AvgApprovalSeconds,
	}, nil
}

// AttachmentDownloadURL is the resolver for the attachmentDownloadURL field.
func (r *queryResolver) AttachmentDownloadURL(ctx context.Context, requestID string, attachmentID string) (string, error) {
	v, err := viewerFromContext(ctx)
	if err != nil {
		return "", err
	}

	reqID, err := parseUUID(requestID)
	if err != nil {
		return "", fmt.Errorf("invalid request id: %w", err)
	}

	attID, err := parseUUID(attachmentID)
	if err != nil {
		return "", fmt.Errorf("invalid attachment id: %w", err)
	}

	svc := attachmentsuc.Service{
		DB:      r.DB,
		Storage: r.Storage,
	}

	url, err := svc.GetDownloadURL(ctx, v.OrgID, v.UserID, reqID, attID, 15*time.Minute)
	if err != nil {
		if errors.Is(err, attachmentsuc.ErrForbidden) {
			return "", fmt.Errorf("forbidden: you don't have permission to download this attachment")
		}
		if errors.Is(err, attachmentsuc.ErrNotFound) {
			return "", fmt.Errorf("attachment not found")
		}
		return "", err
	}

	return url, nil
}

// Submitter is the resolver for the submitter field.
func (r *requestResolver) Submitter(ctx context.Context, obj *model.Request) (*model.User, error) {
	// created_by_user_id がnilの場合はnilを返す
	if obj.CreatedByUserID == nil {
		return nil, nil
	}

	userID, err := parseUUID(*obj.CreatedByUserID)
	if err != nil {
		return nil, err
	}

	q, err := r.queries()
	if err != nil {
		return nil, err
	}

	user, err := q.GetUserByID(ctx, userID)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, nil
		}
		return nil, err
	}

	return &model.User{
		UserID: user.ID.String(),
		OrgID:  "", // ユーザーは複数の組織に所属できるため、ここでは空
		Name:   &user.Name,
		Email:  &user.Email,
	}, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Request returns generated.RequestResolver implementation.
func (r *Resolver) Request() generated.RequestResolver { return &requestResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type requestResolver struct{ *Resolver }
